# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the Actions tab

# Allow GITHUB_TOKEN to create a GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Or your preferred Node.js LTS version
          cache: "npm" # Use 'yarn' if you use yarn package manager

      - name: Install dependencies
        run: npm install # Or 'yarn install' if using yarn

      - name: Determine Vite base path
        id: base_path
        run: |
          if [ "${{ github.repository }}" = "${{ github.repository_owner }}/${{ github.repository_owner }}.github.io" ]; then
            echo "BASE_URL=/" >> $GITHUB_OUTPUT
          else
            echo "BASE_URL=/${{ github.event.repository.name }}/" >> $GITHUB_OUTPUT
          fi

      - name: Build application
        run: npm run build -- --base=${{ steps.base_path.outputs.BASE_URL }}
        # If your build script is just 'vite build' and not in package.json, you might use:
        # run: npx vite build --base=${{ steps.base_path.outputs.BASE_URL }}
        # Assumes your package.json has a "build" script like "vite build" or "tsc && vite build"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Vite's default output directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
